# -*- coding: utf-8 -*-
"""student_burnout_full_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QR8FEOSV8bF3L87rG-3B05cPizY55IID
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix,
    mean_absolute_error, mean_squared_error, r2_score
)
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from xgboost import XGBRegressor

df = pd.read_csv("/content/synthetic_student_behaviour.csv")
print(df.head())

df["burnout_level"] = df["burnout_level"].map({"Low": 0, "Medium": 1, "High": 2})
df = df.fillna(df.mean(numeric_only=True))

features = [
    "lms_logins_per_week",
    "avg_submission_delay_days",
    "attendance_percentage",
    "inactivity_gap_days",
    "night_activity_ratio",
    "study_time_variance",
    "sentiment_score",
    "feedback_negativity_flag",
    "past_sem_gpa",
    "gpa_drop_rate"
]

X = df[features]
y_burnout = df["burnout_level"]
y_dropout = df["dropout_probability"]

df["engagement_index"] = (
    0.5*(df["lms_logins_per_week"] / df["lms_logins_per_week"].max()) +
    0.5*(1 - (df["avg_submission_delay_days"] / df["avg_submission_delay_days"].max()))
)

df["stress_score"] = df["night_activity_ratio"] * df["study_time_variance"]

X["engagement_index"] = df["engagement_index"]
X["stress_score"] = df["stress_score"]

X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X, y_burnout, test_size=0.2, random_state=42
)

clf = RandomForestClassifier(n_estimators=250, random_state=42)
clf.fit(X_train_b, y_train_b)
pred_burnout = clf.predict(X_test_b)

print("Burnout Accuracy:", accuracy_score(y_test_b, pred_burnout))
print("Burnout F1:", f1_score(y_test_b, pred_burnout, average='macro'))
print("Burnout Precision:", precision_score(y_test_b, pred_burnout, average='macro'))
print("Burnout Recall:", recall_score(y_test_b, pred_burnout, average='macro'))
print("Confusion Matrix:\n", confusion_matrix(y_test_b, pred_burnout))

feature_importance = pd.Series(clf.feature_importances_, index=X.columns).sort_values(ascending=False)
print(feature_importance)

X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(
    X, y_dropout, test_size=0.2, random_state=42
)

xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    random_state=42
)
xgb.fit(X_train_d, y_train_d)
pred_dropout = xgb.predict(X_test_d)

print("MAE:", mean_absolute_error(y_test_d, pred_dropout))
print("RMSE:", np.sqrt(mean_squared_error(y_test_d, pred_dropout)))
print("R²:", r2_score(y_test_d, pred_dropout))

cluster_features = df[["engagement_index", "stress_score", "attendance_percentage"]]
kmeans = KMeans(n_clusters=3, random_state=42)
df["cluster_label"] = kmeans.fit_predict(cluster_features)
print(df["cluster_label"].value_counts())

plt.figure(figsize=(14, 10))
sns.heatmap(df.corr(), cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.savefig("1_correlation_heatmap.png", dpi=300)
plt.close()

for col in features:
    plt.figure(figsize=(8, 5))
    sns.histplot(df[col], kde=True)
    plt.title(f"Distribution of {col}")
    plt.savefig(f"dist_{col}.png", dpi=300)
    plt.close()

plt.figure(figsize=(8, 5))
sns.boxplot(x=df["burnout_level"], y=df["dropout_probability"])
plt.title("Dropout Probability vs Burnout Level")
plt.savefig("dropout_vs_burnout.png", dpi=300)
plt.close()

plt.figure(figsize=(8, 6))
sns.scatterplot(
    x=df["engagement_index"],
    y=df["stress_score"],
    hue=df["cluster_label"],
    palette="viridis"
)
plt.title("Behavioural Clusters")
plt.savefig("clusters.png", dpi=300)
plt.close()

df.to_csv("final_output_predictions.csv", index=False)
print("Saved → final_output_predictions.csv")